package rekisteri;
// Generated by ComTest BEGIN
import static org.junit.Assert.*;
import org.junit.*;
import rekisteri.*;
// Generated by ComTest END

/**
 * Test class made by ComTest
 * @version 2019.04.22 16:37:39 // Generated by ComTest
 *
 */
public class KirjatTest {



  // Generated by ComTest BEGIN
  /** test22 */
  @Test
  public void test22() {    // Kirjat: 22
    Kirjat testi = new Kirjat(); 
  } // Generated by ComTest END
}